spring:
    datasource:
        url: jdbc:mysql://db:3306/pdd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: mysql_root_password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                enable_lazy_load_no_trans: true
    thymeleaf:
        cache: false
    redis:
        host: redis
        port: 6379
    session:
        store-type: redis


server:
    port: 8080


logging:
    level:
        org.springframework: error
        com.calm: info
    file:
        max-size: 10MB
        max-history: 60
    path: logs
