spring:
    datasource:
        url: jdbc:mysql://localhost:3306/pdd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: mysql_root_password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                enable_lazy_load_no_trans: true
    freemarker:
        template-loader-path: classpath:/templates
        suffix: .ftl
        cache: false
        expose-request-attributes: true
    redis:
        host: localhost
        port: 6379
        timeout: 2000
    session:
        store-type: redis
        timeout: 86400
    cache:
        redis:
            time-to-live: 2000


server:
    port: 8080


logging:
    level:
        org.springframework: error
        com.calm: info
        #org.hibernate.SQL: DEBUG
        #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        #org.hibernate.type: TRACE
    file:
        max-size: 10MB
        max-history: 60
    path: logs
