spring:
    datasource:
        url: jdbc:mysql://db:3306/pdd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: pdd
        password: mysql_password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                enable_lazy_load_no_trans: true
    freemarker:
        template-loader-path: classpath:/templates
        suffix: .ftl
        cache: true
        expose-request-attributes: true
    redis:
        host: redis
        port: 6379
        timeout: 2000
    session:
        store-type: redis
        timeout: 86400
    cache:
        redis:
            time-to-live: 600000


server:
    port: 8090


logging:
    level:
        org.springframework: error
        com.calm: info
    file:
        max-size: 10MB
        max-history: 60
    path: logs
