properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'master'
    }
    triggers {
        pollSCM('* * * * *')
    }
    stages {
        stage('configure') {
            steps {
                sh 'cp dist/docker/.env.template dist/docker/.env'
            }
        }
        stage('maven build') {
            steps {
                sh 'mvn package'
            }
        }
    }
}