properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'master'
    }
    triggers {
        pollSCM('* * * * *')
    }
    stages {
        stage('configure') {
            steps {
                sh 'cp dist/docker/.env.template dist/docker/.env'
            }
        }
        stage('maven build') {
            steps {
                sh 'mvn clean package'
                //sh 'sudo chown 1000 -R target/build'
            }
        }
        stage('docker build') {
            steps {
                dir('target/build/docker') {
                    sh 'docker-compose build --no-cache'
                    sh 'docker-compose up -d'
                }
            }
        }
    }
}