[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="authUser" type="com.calm.pdd.core.model.entity.User" --]
[#-- @ftlvariable name="currentProgressUnit" type="com.calm.pdd.core.model.session.QuestionProgressUnit" file="templates/question.ftl" --]
[#-- @ftlvariable name="progress" type="com.calm.pdd.core.model.session.QuestionProgress" file="templates/question.ftl" --]
[#-- @ftlvariable name="question" type="com.calm.pdd.core.model.entity.Question" file="templates/question.ftl" --]
[#-- @ftlvariable name="sections" type="java.util.List<com.calm.pdd.core.model.entity.Section>" file="templates/sections.ftl" --]
